### ISSUE TITLE
v10

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#1034]
```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/1122
- [ ] https://github.com/zeta-chain/node/issues/1013
- [ ] https://github.com/zeta-chain/node/issues/601
- [ ] https://github.com/zeta-chain/node/issues/603
- [ ] https://github.com/zeta-chain/zeta-node/issues/575
- [ ] https://github.com/zeta-chain/node/issues/1037
- [ ] https://github.com/zeta-chain/node/issues/1039
- [ ] https://github.com/zeta-chain/node/issues/935
- [ ] https://github.com/zeta-chain/node/issues/1059
- [ ] https://github.com/zeta-chain/node/issues/956
- [ ] https://github.com/zeta-chain/node/issues/1058
- [ ] https://github.com/zeta-chain/node/issues/1021
- [ ] https://github.com/zeta-chain/node/issues/1054
- [ ] https://github.com/zeta-chain/node/issues/1115
- [ ] https://github.com/zeta-chain/node/issues/1116
- [ ] https://github.com/zeta-chain/node/issues/994
- [ ] https://github.com/zeta-chain/node/issues/993
- [ ] https://github.com/zeta-chain/node/issues/932
- [ ] https://github.com/zeta-chain/node/issues/1103
- [ ] https://github.com/zeta-chain/node/issues/1114
- [ ] https://github.com/zeta-chain/node/issues/1117
- [ ] https://github.com/zeta-chain/node/issues/1136
- [ ] https://github.com/zeta-chain/node/issues/1138
- [ ] https://github.com/zeta-chain/node/issues/1165
```

Planned: mid September.

**Comment by fadeev** [comment]
Go through the audit issues: https://github.com/zeta-chain/node/issues/638
