### ISSUE TITLE
v11-old

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#1035]
```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/1225
- [ ] https://github.com/zeta-chain/node/issues/1255
- [ ] https://github.com/zeta-chain/node/issues/1278
- [ ] https://github.com/zeta-chain/node/issues/1299
- [ ] https://github.com/zeta-chain/node/issues/1248
- [ ] https://github.com/zeta-chain/node/issues/1217
- [ ] https://github.com/zeta-chain/node/issues/1109
- [ ] https://github.com/zeta-chain/node/issues/1300
- [ ] https://github.com/zeta-chain/node/issues/1313
- [ ] https://github.com/zeta-chain/node/issues/1314
- [ ] https://github.com/zeta-chain/node/issues/1327
- [ ] #1349
- [ ] #1348
- [ ] #1347
- [ ] https://github.com/zeta-chain/node/issues/1331
```

**Comment by lumtis** [comment]
Closing in favor of new milestone: https://github.com/zeta-chain/node/issues/1332
