### ISSUE TITLE
TSS migration: coordinating with OS set

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#1059]
```[tasklist]
### Tasks
- [x] Add new observer keysigner and do keygen
- [x] Switch from old TSS address to the new one
- [ ] https://github.com/zeta-chain/node/issues/1339
```

**Comment by kingpinXD** [comment]
We have test this with v12 on `mock mainnet`. Similar steps can be followed in Athens 3 . 
@lumtis  @CharlieMc0  , is there anything that's blocking us
