### ISSUE TITLE
stricter checks in block header

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/node#1133]
* check previous block header
* no skipping 
* fork choice rule? 

```[tasklist]
### Tasks
- [ ] Add a notion of tip block number to state variable (the latest block number of the header that were accepted)
- [ ] Enforce no skipping of block headers in zetaclients 
- [ ] Enforce no skipping of block headers in zetacore
```

**Comment by lumtis** [comment]
> Check previous block header

Does this mean a fully on-chain check of the previous block header? we compute the hash of the previously added block header and it must be equal to the provided parent hash?

> Fork choice rule?

For chains with orphaned block such as Bitcoin, I may think the best would be to consider Nakamoto consensus: the valid chain is the longest one
Several children can get added to the new block but we store in the protocol which chain is the longest one, this is the only one that can verify proof (we would also need to consider confirmation number)

> Add a notion of tip block number to state variable (the latest block number of the header that were accepted)

Is `tip` a type -> `top`?
