### ISSUE TITLE
v10.1

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#1141]
```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/1187
- [ ] https://github.com/zeta-chain/node/issues/1216
- [ ] https://github.com/zeta-chain/node/issues/1221
- [ ] https://github.com/zeta-chain/node/issues/1233
- [ ] https://github.com/zeta-chain/node/issues/1242
- [ ] https://github.com/zeta-chain/node/issues/1249
- [ ] https://github.com/zeta-chain/node/issues/1253
- [ ] https://github.com/zeta-chain/node/issues/1256
- [ ] https://github.com/zeta-chain/node/issues/1258
- [ ] https://github.com/zeta-chain/node/pull/1143
- [ ] https://github.com/zeta-chain/node/pull/1265
```
