### ISSUE TITLE
Improve `ZetaClient` tests and coverage

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1203]
General improvement for ZetaClient testing and coverage.

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/1154
- [ ] https://github.com/zeta-chain/node/issues/1155
- [ ] https://github.com/zeta-chain/node/issues/1156
- [ ] https://github.com/zeta-chain/node/issues/1157
- [ ] https://github.com/zeta-chain/node/issues/1158
- [ ] https://github.com/zeta-chain/node/issues/1196
- [ ] https://github.com/zeta-chain/node/issues/1197
- [ ] https://github.com/zeta-chain/node/issues/1198
- [ ] https://github.com/zeta-chain/node/issues/1199
- [ ] https://github.com/zeta-chain/node/issues/1200
- [ ] https://github.com/zeta-chain/node/issues/1201
- [ ] https://github.com/zeta-chain/node/issues/1202
- [ ] https://github.com/zeta-chain/node/issues/1918
```

**Comment by lumtis** [comment]
Closing for more described task: https://github.com/zeta-chain/node/issues/2028
