### ISSUE TITLE
consolidate builds 

### ISSUE THREAD

**Issue by CharlieMc0** [zeta-chain/node#1331]
We create a new binary for each environment - PRIVNET, TESTNET, and MAINNET. 

This results in a a lot of binaries for each release and is difficult to manage. 

It would be easier for all operators if they had one zetacored binary and could set the network from a flag or config file.

**Comment by lumtis** [comment]
# TODO

- [ ] Remove `BlockOneDeploySystemContracts`
- [ ] Find alternative to `BlockOneDeploySystemContracts` => add it as part of `initGenesis` or automated script (or no alternative since testnets are launched)
- [ ] Add `CoreParams` as part of genesis state
- [ ] Consolidate config (`cmd/config_mainnet`)
- [ ] Consolidate ZetaClient config
- [ ] Group all default chain together
- [ ] Remove PRIVNET build for smoketests
- [ ] Remove TESTNET in CLI helper tests, intx tracket and outtx tracker tests
- [ ] Delete `test_privnet` and `test_testnet`
- [ ] Remove build-specific make commands
