### ISSUE TITLE
Add Sepolia support

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#1463]
```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node-private/issues/69
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/108
- [ ] https://github.com/zeta-chain/networks/issues/31
- [x] Create Sepolia ETH/WZETA internal pool and add liquidity
- [x] Add Sepolia ETH as a supported foreign coin
- [ ] https://github.com/zeta-chain/node/issues/1455
- [ ] https://github.com/zeta-chain/node/issues/1475
- [x] Update ZetaClient config with Sepolia RPC
```
