### ISSUE TITLE
General E2E testing improvement

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1481]
This EPIC includes tasks for making smoke tests :

- more reliable, less false positive failure
- faster
- more customizable, ability to run on different networks, etc...

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/1408
- [ ] https://github.com/zeta-chain/node/issues/1398
- [ ] https://github.com/zeta-chain/node/issues/1227
- [ ] https://github.com/zeta-chain/node/issues/1208
- [ ] https://github.com/zeta-chain/node/issues/1482
- [ ] https://github.com/zeta-chain/node/issues/1483
- [ ] https://github.com/zeta-chain/node/issues/1492
- [ ] https://github.com/zeta-chain/node/issues/1470
- [ ] https://github.com/zeta-chain/node/issues/1462
- [ ] https://github.com/zeta-chain/node/issues/1461
- [ ] https://github.com/zeta-chain/node/issues/1460
- [ ] https://github.com/zeta-chain/node/issues/1459
- [ ] https://github.com/zeta-chain/node/issues/1649
```

**Comment by lumtis** [comment]
Closing in favor of https://github.com/zeta-chain/node/issues/1720
