### ISSUE TITLE
ZetaClient Code Structure Revamp

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1611]
This EPIC includes issues or a list of issues for ZetaClient revamp.

This includes:
- Test coverage
- Modularity and better maintainability

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/2503
- [ ] https://github.com/zeta-chain/node/issues/2021
- [ ] https://github.com/zeta-chain/node/issues/2023
- [ ] https://github.com/zeta-chain/node/issues/2025
- [ ] https://github.com/zeta-chain/node/issues/2437
- [ ] https://github.com/zeta-chain/node/issues/2318
- [ ] https://github.com/zeta-chain/node/issues/1761
- [ ] https://github.com/zeta-chain/node/issues/2084
- [ ] https://github.com/zeta-chain/node/issues/2085
- [ ] https://github.com/zeta-chain/node/issues/2322
- [ ] https://github.com/zeta-chain/node/issues/1837
```

### Completed

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/1397
- [ ] https://github.com/zeta-chain/node/issues/1904
- [ ] https://github.com/zeta-chain/node/issues/2519
- [ ] https://github.com/zeta-chain/node/issues/2086
- [ ] https://github.com/zeta-chain/node/issues/2526
- [ ] https://github.com/zeta-chain/node/issues/2027
- [ ] https://github.com/zeta-chain/node/issues/2026
- [ ] https://github.com/zeta-chain/node/issues/2022
- [ ] https://github.com/zeta-chain/node/issues/2024
- [ ] https://github.com/zeta-chain/node/issues/1534
- [ ] https://github.com/zeta-chain/node/issues/1609
- [ ] https://github.com/zeta-chain/node/issues/1608
- [ ] https://github.com/zeta-chain/node/issues/1607
- [ ] https://github.com/zeta-chain/node/issues/1246
- [ ] https://github.com/zeta-chain/node/issues/1573
- [ ] https://github.com/zeta-chain/node/issues/1769
- [ ] https://github.com/zeta-chain/node/issues/1770
- [ ] https://github.com/zeta-chain/node/issues/1633
- [ ] https://github.com/zeta-chain/node/issues/1678
- [ ] https://github.com/zeta-chain/node/issues/1807
- [ ] https://github.com/zeta-chain/node/issues/1832
- [ ] https://github.com/zeta-chain/node/issues/1887
- [ ] https://github.com/zeta-chain/node/issues/1883
- [ ] https://github.com/zeta-chain/node/issues/1888
- [ ] https://github.com/zeta-chain/node/issues/2126
- [ ] https://github.com/zeta-chain/node/issues/2180
- [ ] https://github.com/zeta-chain/node/issues/1643
- [ ] https://github.com/zeta-chain/node/issues/2020
```

```[tasklist]
### V2 Revamp
- [ ] https://github.com/zeta-chain/node/issues/2015
- [ ] https://github.com/zeta-chain/node/issues/3115
- [ ] https://github.com/zeta-chain/node/issues/3108
- [ ] https://github.com/zeta-chain/node/issues/3112
- [ ] https://github.com/zeta-chain/node/issues/2381
- [ ] https://github.com/zeta-chain/node/issues/3119
- [ ] https://github.com/zeta-chain/node/issues/2589
- [ ] https://github.com/zeta-chain/node/issues/3096
- [ ] https://github.com/zeta-chain/node/issues/1901
- [ ] https://github.com/zeta-chain/node/issues/3109
- [ ] https://github.com/zeta-chain/node/issues/3110
- [ ] https://github.com/zeta-chain/node/issues/2019
- [ ] https://github.com/zeta-chain/node/issues/2029
- [ ] https://github.com/zeta-chain/node/issues/3111
```
