### ISSUE TITLE
`v12.3.0`

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1683]
```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/1682
- [ ] https://github.com/zeta-chain/node/issues/1681
- [ ] https://github.com/zeta-chain/node/issues/1679
- [ ] https://github.com/zeta-chain/node/issues/1688
- [ ] https://github.com/zeta-chain/node/issues/1690
- [ ] https://github.com/zeta-chain/node/issues/1698
- [ ] https://github.com/zeta-chain/node/issues/1192
- [ ] https://github.com/zeta-chain/node/issues/1707
- [ ] https://github.com/zeta-chain/node/issues/1721
- [ ] https://github.com/zeta-chain/node/issues/1701
- [ ] https://github.com/zeta-chain/node/issues/1732
- [ ] https://github.com/zeta-chain/node/issues/1738
```

**Comment by lumtis** [comment]
@ws4charlie please add hotfix task

**Comment by ws4charlie** [comment]
> @ws4charlie please add hotfix task

done
