### ISSUE TITLE
Improve the blockchain modularity

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1711]
Goal: each module of the blockchain should serve a specific purpose with a well defined API.

This epic group tasks to achieve this goal. Moving state variables, messages in their respective module. Adding new module if a current functionality serves a goal different from the module purpose.

The overall end goal is to simplify the codebase, make it more intuitive and reduce coupling between the modules.

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/1512
- [ ] https://github.com/zeta-chain/node/issues/1170
- [ ] https://github.com/zeta-chain/node/issues/1685
- [ ] https://github.com/zeta-chain/node/issues/1699
- [ ] https://github.com/zeta-chain/node/issues/1491
- [ ] https://github.com/zeta-chain/node/issues/1714
- [ ] https://github.com/zeta-chain/node/issues/1716
- [ ] https://github.com/zeta-chain/node/issues/1806
- [ ] https://github.com/zeta-chain/node/issues/1236
- [ ] https://github.com/zeta-chain/node/issues/1924
- [ ] https://github.com/zeta-chain/node/issues/1926
- [ ] https://github.com/zeta-chain/node/issues/1927
```
