### ISSUE TITLE
Streamline E2E testing processes

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1720]
The goal of this epic is to streamline our E2E testing processes, how to extensively and effectively test the system from development to production.

It includes tasks that improve code quality of the current E2E tests, adds new E2E test types, adding new CI actions, and tooling for testing.

Once this epic is completed, we should have a complete streamlined and documented E2E testing process.

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/1649
- [ ] https://github.com/zeta-chain/node/issues/1651
- [ ] https://github.com/zeta-chain/node/issues/1668
- [ ] https://github.com/zeta-chain/node/issues/1670
- [ ] https://github.com/zeta-chain/node/issues/1686
- [ ] https://github.com/zeta-chain/node/issues/1618
- [ ] https://github.com/zeta-chain/node/issues/1719
- [ ] https://github.com/zeta-chain/node/issues/1454
- [ ] https://github.com/zeta-chain/node/issues/1623
- [ ] https://github.com/zeta-chain/node/issues/1461
- [ ] https://github.com/zeta-chain/node/issues/1469
- [ ] https://github.com/zeta-chain/node/issues/1614
- [ ] https://github.com/zeta-chain/node/issues/1704
- [ ] https://github.com/zeta-chain/node/issues/1725
- [ ] https://github.com/zeta-chain/node/pull/1694
- [ ] https://github.com/zeta-chain/node/issues/1829
- [ ] https://github.com/zeta-chain/node/issues/1854
- [ ] https://github.com/zeta-chain/node/issues/1859
- [ ] https://github.com/zeta-chain/node/issues/1896
- [ ] https://github.com/zeta-chain/node/issues/1965
- [ ] https://github.com/zeta-chain/node/issues/1981
```
