### ISSUE TITLE
Implement `WithdrawAndCall` as part of the ZRC20 interface

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1779]
This epic tracks the progress for the `WithdrawAndCall` functionality. Tasks for its completion are not tracked yet. We create this issue so a link can already be given to track the progress

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/161
- [ ] https://github.com/zeta-chain/node/issues/1778
- [ ] https://github.com/zeta-chain/node/issues/1430
- [ ] https://github.com/zeta-chain/node/issues/2170
- [ ] https://github.com/zeta-chain/node/issues/2171
- [ ] https://github.com/zeta-chain/node/issues/2172
- [ ] https://github.com/zeta-chain/node/issues/2173
- [ ] https://github.com/zeta-chain/node/issues/2174
- [ ] https://github.com/zeta-chain/node/issues/2280
- [ ] https://github.com/zeta-chain/node/issues/2281
```

**Comment by lumtis** [comment]
No longer relevant with system contract V2 implementation: https://github.com/zeta-chain/node/issues/2281
