### ISSUE TITLE
Supporting message passing in/out of ZetaChain

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1799]
Feature request: https://github.com/zeta-chain/node/issues/1507

This epic tracks the necessary tasks to complete the feature of supporting message passing:
- External chain -> Zeta
- Zeta -> External chain

The feature adding new workflow paths in the inbound/outbound execution logic which would requires us to streamline the code related to this workflow.

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/1802
- [ ] https://github.com/zeta-chain/node/issues/1800
- [ ] https://github.com/zeta-chain/node/issues/1801
- [ ] https://github.com/zeta-chain/node/issues/1803
- [ ] https://github.com/zeta-chain/node/issues/1804
- [ ] https://github.com/zeta-chain/node/issues/1834
- [ ] https://github.com/zeta-chain/node/issues/1835
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/138
- [ ] https://github.com/zeta-chain/security/issues/82
- [ ] https://github.com/zeta-chain/node/issues/1999
- [ ] https://github.com/zeta-chain/security/issues/96
```
