### ISSUE TITLE
Upgrade Cosmos SDK to `v0.47.10`

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1928]
This epic lists the set of tasks to complete in order to upgrade the blockchain to using [v0.47.10](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.47.10) (latest 47.x version)

It follows these steps: https://github.com/cosmos/cosmos-sdk/blob/v0.47.10/UPGRADING.md
And some other various tasks

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/848
- [ ] https://github.com/zeta-chain/node/issues/1929
- [ ] https://github.com/zeta-chain/node/issues/1930
- [ ] https://github.com/zeta-chain/node/issues/1931
- [ ] https://github.com/zeta-chain/node/issues/1932
- [ ] https://github.com/zeta-chain/node/issues/2065
- [ ] https://github.com/zeta-chain/node/issues/2091
- [ ] https://github.com/zeta-chain/node/issues/2120
- [ ] https://github.com/zeta-chain/node/issues/2121
```

**Comment by gartnera** [comment]
Reopening due to upgrade issues

**Comment by gartnera** [comment]
Upgrade issues appear to be resolved
