### ISSUE TITLE
Open-source the repo

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/node#196]
```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/zeta-node/issues/717
- [ ] https://github.com/zeta-chain/zeta-node/issues/519
- [ ] https://github.com/zeta-chain/zeta-node/issues/564
- [ ] https://github.com/zeta-chain/zeta-node/issues/566
- [ ] https://github.com/zeta-chain/zeta-node/issues/567
- [ ] https://github.com/zeta-chain/zeta-node/issues/568
- [ ] https://github.com/zeta-chain/zeta-node/issues/586
- [x] Cleanup sensitive info
- [ ] Make sure the `develop` branch is protected
- [ ] Pin the repo in the zeta-chain org
```

**Comment by lumtis** [comment]
Closing as it looks no longer relevant.
