### ISSUE TITLE
Add an admin local E2E test to test TSS migration

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1965]
**Describe the Issue**
Add a local E2E test that can do the following:

- Start the local environment and send cctxs normally
- Stop cctxs
- Perform a TSS migration. There are several options we can consider implementing:
  - New observer added
  - Observer removed
  - Observer updated
- Check the TSS can migrate funds
- New cctxs can be created

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/2370
- [ ] https://github.com/zeta-chain/node/issues/2371
- [ ] https://github.com/zeta-chain/node/issues/2441
- [ ] https://github.com/zeta-chain/node/issues/2442
- [ ] https://github.com/zeta-chain/node/issues/2443
- [ ] https://github.com/zeta-chain/node/issues/2444
- [ ] https://github.com/zeta-chain/node/issues/2455
- [ ] https://github.com/zeta-chain/node/issues/2487
- [ ] https://github.com/zeta-chain/node/issues/2492
```

**Comment by kingpinXD** [comment]
Add, Remove observer is a separate functionality from TSS migration and should be tested separately .
 It would make sense to create a e2e test first which does the following 
 - Sets a new keygen 
 - Restarts zeta-clients so that they pick up the new keygen and generate TSS 
 - Migrate TSS funds 
 - Update TSS address 
 - Test cross-chain transactions

**Comment by lumtis** [comment]
>Add, Remove observer is a separate functionality from TSS migration and should be tested separately .
It would make sense to create a e2e test first which does the following
- Sets a new keygen
- Restarts zeta-clients so that they pick up the new keygen and generate TSS
- Migrate TSS funds
- Update TSS address
- Test cross-chain transactions

This can be a first step but why not putting everything under the same test in the end?
