### ISSUE TITLE
Improve `emissions` module and make it more flexible for a permissionless set

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#2105]
**Describe the Issue**
This epic track tasks to improve the `emissions` module and allow moving toward a design when adding a new observer in the set would follow more permissionless rule.

- Adding more parameter to configure the rewards
- Implement full mechanism for deincentivizing non-correct behavior

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/1898
- [ ] https://github.com/zeta-chain/node/issues/1897
- [ ] https://github.com/zeta-chain/node/issues/1792
- [ ] https://github.com/zeta-chain/node/issues/1654
- [ ] https://github.com/zeta-chain/node/issues/942
- [ ] https://github.com/zeta-chain/node/issues/1852
- [ ] https://github.com/zeta-chain/node/issues/1813
- [ ] https://github.com/zeta-chain/node/issues/3078
```

**Comment by lumtis** [comment]
Putting this v18 for now, we will reevaluate priority after v17 upgrade
