### ISSUE TITLE
Integrate Solana into testnet

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#2401]
**Describe the Issue**
This EPIC groups tasks toward integration of Solana into testnet.

Ability to depositAndCall/withdraw SOL with omnichain smart contracts

TODO: create corresponding issues:
- localnet
- ZetaClient changes
- ZetaCore changes
- Solana contracts

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/2398
- [ ] https://github.com/zeta-chain/node/issues/2404
- [ ] https://github.com/zeta-chain/node/issues/2407
- [ ] https://github.com/zeta-chain/node/issues/2405
- [ ] https://github.com/zeta-chain/node/issues/2406
- [ ] https://github.com/zeta-chain/node/issues/2413
- [ ] https://github.com/zeta-chain/node/issues/2414
- [ ] https://github.com/zeta-chain/protocol-contracts-solana/issues/5
- [ ] https://github.com/zeta-chain/protocol-contracts-solana/issues/6
```

**Comment by lumtis** [comment]
All task completed
