### ISSUE TITLE
Support protocol contract V2

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#2402]
This EPIC groups issues to complete support for system contract V2 on the protocol.

- Completing the smart contracts
- Updating protocol and ZetaClient to use the contracts
- Establishing migration plan and implementing protocol features to enable migration (example: migrate ERC20Custody migration)
- Track some problems with current smart contracts to ensure new architecture fix these

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/198
- [ ] https://github.com/zeta-chain/node/issues/2280
- [ ] https://github.com/zeta-chain/node/issues/2348
- [ ] https://github.com/zeta-chain/node/issues/2206
```
