### ISSUE TITLE
Integrate Solana Mainnet

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#2506]
**Describe the Issue**
This EPIC is an extension of https://github.com/zeta-chain/node/issues/2401

It is used to track every tasks necessary to fully support Solana on Mainnet
- Integration
- Optimization to do after testnet integration
- Any bugs occuring during testnet experimentation

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/2401
- [ ] https://github.com/zeta-chain/protocol-contracts-solana/issues/8
- [ ] https://github.com/zeta-chain/node/issues/2659
- [ ] https://github.com/zeta-chain/node/issues/2507
- [ ] https://github.com/zeta-chain/node/issues/2508
- [ ] https://github.com/zeta-chain/node/issues/2614
- [ ] https://github.com/zeta-chain/node/issues/2606
- [ ] https://github.com/zeta-chain/node/issues/2692
```
