### ISSUE TITLE
Implement functionalities to allow system contracts migration

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#2551]
**Describe the Issue**
Creating sub-epic to make this one cleaner: https://github.com/zeta-chain/node/issues/2402

This epic focus specifically on the necessary functionalities allowing to migrate to new system contract once the architecture is implemented

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/2489
- [ ] https://github.com/zeta-chain/node/issues/2281
- [ ] https://github.com/zeta-chain/node/issues/2280
- [ ] https://github.com/zeta-chain/node/issues/2553
- [ ] https://github.com/zeta-chain/node/issues/2677
```
