### ISSUE TITLE
Implement interaction with system contract v2

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#2552]
**Describe the Issue**
Creating sub-epic to make this one cleaner: https://github.com/zeta-chain/node/issues/2402

This epic focus specifically on refactoring the code to allow interaction with the new protocol contract architecture.

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/2577
- [ ] https://github.com/zeta-chain/node/issues/2554
- [ ] https://github.com/zeta-chain/node/issues/2439
- [ ] https://github.com/zeta-chain/node/issues/2490
- [ ] https://github.com/zeta-chain/node/issues/2491
- [ ] https://github.com/zeta-chain/node/issues/2601
- [ ] https://github.com/zeta-chain/node/issues/2602
- [ ] https://github.com/zeta-chain/node/issues/2622
- [ ] https://github.com/zeta-chain/node/issues/2623
- [ ] https://github.com/zeta-chain/node/issues/2624
- [ ] https://github.com/zeta-chain/node/issues/2625
- [ ] https://github.com/zeta-chain/node/issues/2660
- [ ] https://github.com/zeta-chain/node/issues/2668
- [ ] https://github.com/zeta-chain/node/issues/2669
```
