### ISSUE TITLE
💎 TON testnet integration 

### ISSUE THREAD

**Issue by swift1337** [zeta-chain/node#2716]
# Description
This EPIC groups tasks toward integration of [TON](https://ton.org/) into testnet. Features:

User Actions
- `donate()`
- `deposit()`
- `deposit_and_call()`
- `withdraw()` (on behalf of TSS)

Governance actions
- `enable_deposits()`
- `update_tss()`
- `update_code()`

## High-Level task list
- Implement Gateway contract on TON using [FunC](https://docs.ton.org/develop/func/overview) & [Blueprint](https://github.com/ton-org/blueprint)
  - Create `zeta-chain/protocol-contracts-ton` repository
  - Determine gas economics for TON integration (including storage fees)
  - Support TSS signature
- TON localnet integration
- Implement TON `observer`
- TON `deposit()` E2E test
- Implement TON `signer`
- TON `withdraw()` E2E test
- Provision configuration changes (chain_id, chain, observer_chain_params, ...)
- Deploy contract on testnet 
- DevX: prepare docs, code samples, tutorials, ...

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/2718
- [ ] https://github.com/zeta-chain/node/issues/2720
- [ ] https://github.com/zeta-chain/node/issues/2757
- [ ] https://github.com/zeta-chain/node/issues/2808
- [ ] https://github.com/zeta-chain/protocol-contracts-ton/issues/14
- [ ] https://github.com/zeta-chain/protocol-contracts-ton/issues/9
- [ ] https://github.com/zeta-chain/protocol-contracts-ton/issues/13
- [ ] https://github.com/zeta-chain/node/issues/2807
- [ ] https://github.com/zeta-chain/node/issues/2809
- [ ] https://github.com/zeta-chain/node/issues/3057
- [ ] https://github.com/zeta-chain/node/issues/2935
- [ ] https://github.com/zeta-chain/node/issues/2946
- [ ] https://github.com/zeta-chain/node/issues/3044
- [ ] https://github.com/zeta-chain/node/issues/2810
- [ ] https://github.com/zeta-chain/node/issues/3436
```

**Comment by lumtis** [comment]
Will close this as the last remaining issue is just operation tracker
