### ISSUE TITLE
Protocol Contract V2 follow-up tasks

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#2745]
This EPIC lists issues as a follow up to the base integration of Protocol Contracts V2.

It contains improvements and considerations to be implemented in the short term to improve stability of the new environment.
```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/2037
- [ ] https://github.com/zeta-chain/node/issues/2652
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/245
- [ ] https://github.com/zeta-chain/node/issues/2557
- [ ] https://github.com/zeta-chain/node/issues/2474
- [ ] https://github.com/zeta-chain/node/issues/2711
- [ ] https://github.com/zeta-chain/node/issues/2712
- [ ] https://github.com/zeta-chain/node/issues/2967
- [ ] https://github.com/zeta-chain/node/issues/2648
- [ ] https://github.com/zeta-chain/node/issues/2713
```
