### ISSUE TITLE
Solana Improvement Iteration 1

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#2746]
This EPIC lists issues to prioritize as a next iteration for improving the integration:

EPIC can eventually be renamed if we find a more descriptive name of the overall purpose.

- More reliability/testing
- Better DevEx
- Eventual issues from audit and testnet testing
```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/2604
- [ ] https://github.com/zeta-chain/protocol-contracts-solana/issues/19
- [ ] https://github.com/zeta-chain/protocol-contracts-solana/issues/18
- [ ] https://github.com/zeta-chain/node/issues/2747
```
