### ISSUE TITLE
Support authenticated calls on connected chains

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#2876]
Integrate in the protocol, the ability for call a predefined hook `onCall` on connected chains that contains a `messageContext` to identify the caller from ZetaChain.

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/344
- [ ] https://github.com/zeta-chain/node/issues/2877
- [ ] https://github.com/zeta-chain/localnet/issues/37
```
