### ISSUE TITLE
Supporting SPL tokens on Solana

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#2936]
**Describe the Issue**

Add support to whitelist SPL tokens on Solana and represent those as ZRC20 of type ERC20 on ZetaChain.

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/protocol-contracts-solana/issues/9
- [ ] https://github.com/zeta-chain/protocol-contracts-solana/issues/28
- [ ] https://github.com/zeta-chain/protocol-contracts-solana/issues/33
- [ ] https://github.com/zeta-chain/node/issues/2937
- [ ] https://github.com/zeta-chain/node/issues/2938
- [ ] https://github.com/zeta-chain/node/issues/2939
- [ ] https://github.com/zeta-chain/node/issues/3147
- [ ] https://github.com/zeta-chain/node/issues/3148
```
