### ISSUE TITLE
Supporting smart contract calls on Solana

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#2941]
**Describe the Issue**

Implement ability to use `call` and `withdrawAndCall` with Solana.

Authenticated calls only would be sufficient for an initial implementation.

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/protocol-contracts-solana/issues/30
- [ ] https://github.com/zeta-chain/node/issues/2942
- [ ] https://github.com/zeta-chain/node/issues/2943
- [ ] https://github.com/zeta-chain/node/issues/3443
```
