### ISSUE TITLE
Support advanced abort handling

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#3211]
**Describe the Issue**

To increase the flexibility for developers we should define advanced abort handling logic that allow to define a last fallback for CCTX workflow (when even the revert fails) this add a layer of security to prevent loss of funds and have a recovery logic that is guaranteed to be called.

This EPIC list issues for this idea

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/2713
- [ ] https://github.com/zeta-chain/node/issues/3168
- [ ] https://github.com/zeta-chain/node/issues/3210
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/429
- [ ] https://github.com/zeta-chain/node/issues/3530
- [ ] https://github.com/zeta-chain/node/issues/3531
- [ ] https://github.com/zeta-chain/node/issues/3532
```
