### ISSUE TITLE
Integrate ZetaConnector with Gateway architecture (protocol v2)

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#3212]
**Describe the Issue**

A v2 of the ZetaConnector was developed in https://github.com/zeta-chain/protocol-contracts but has been disabled for the time being.
This EPIC tracks the effort in order to enable the new ZetaConnector and consolidate all interactions around the gateway.

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/357
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/358
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/394
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/398
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/432
```
