### ISSUE TITLE
Solana code quality and reliability improvement

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#3233]
This EPIC lists different task we should complete to improve the codebase before considering new features integrations like withdrawAndCall

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/protocol-contracts-solana/issues/63
- [ ] https://github.com/zeta-chain/protocol-contracts-solana/issues/62
- [ ] https://github.com/zeta-chain/protocol-contracts-solana/issues/50
- [ ] https://github.com/zeta-chain/protocol-contracts-solana/issues/47
- [ ] https://github.com/zeta-chain/protocol-contracts-solana/issues/46
- [ ] https://github.com/zeta-chain/protocol-contracts-solana/issues/12
- [ ] https://github.com/zeta-chain/protocol-private/issues/189
- [ ] https://github.com/zeta-chain/protocol-private/issues/188
- [ ] https://github.com/zeta-chain/protocol-private/issues/187
- [ ] https://github.com/zeta-chain/protocol-private/issues/186
- [ ] https://github.com/zeta-chain/protocol-private/issues/185
- [ ] https://github.com/zeta-chain/protocol-private/issues/184
- [ ] https://github.com/zeta-chain/protocol-private/issues/183
- [ ] https://github.com/zeta-chain/protocol-private/issues/182
- [ ] https://github.com/zeta-chain/protocol-private/issues/181
- [ ] https://github.com/zeta-chain/protocol-private/issues/180
```
