### ISSUE TITLE
Orchestrator V2

### ISSUE THREAD

**Issue by swift1337** [zeta-chain/node#3304]
# Goals

Improve `zetaclientd` CODE MAINTAINABILITY, RELIABILITY, OBSERVABILITY, and FAULT-TOLERANCE by revamping chain orchestration logic.
```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/3299
- [ ] https://github.com/zeta-chain/node/issues/3303
- [ ] https://github.com/zeta-chain/node/issues/3302
- [ ] https://github.com/zeta-chain/node/issues/3331
- [ ] https://github.com/zeta-chain/node/issues/3330
- [ ] https://github.com/zeta-chain/node/issues/3300
- [ ] https://github.com/zeta-chain/node/issues/3386
- [ ] https://github.com/zeta-chain/node/issues/3301
```
