### ISSUE TITLE
Fungible module call revert

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/node#344]
Currently when inbound CCTX calls zEVM and fails, then the cctx goes directly into "aborted". 

Should have refunded the fungible tokens user sent in, less the gas fees + withdraw fees. 

## Proposed solution

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/zeta-node/issues/742
- [ ] https://github.com/zeta-chain/zeta-node/issues/725
- [ ] https://github.com/zeta-chain/zeta-node/issues/749
```
