### ISSUE TITLE
TSS Keygen & Migration from old keys

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/node#361]
This is a multi-step multi-chain operation and critical to security, and probably needs a big **Barrier** that stops processing new outbound txs and wait for broadcasted txs to be mined and confirmed. 

The barrier will wait for all signed & broadcasted txs to confirm (if not, they need to be cancelled). 

Question: how does zetacore distinguish between pending txs and broadcasted txs? 

Depends on the admin stopping functionality. You need to be able to do certain things during migrations.

## Proposed solution

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/zeta-node/issues/683
- [ ] https://github.com/zeta-chain/node/issues/687
- [ ] https://github.com/zeta-chain/node/issues/1011
- [ ] https://github.com/zeta-chain/node/issues/1026
- [ ] https://github.com/zeta-chain/node/issues/1027
- [ ] https://github.com/zeta-chain/node/issues/1028
- [ ] https://github.com/zeta-chain/node/issues/1052
```

**Comment by kingpinXD** [comment]
WIP DOC : https://www.notion.so/zetachain/TSS-Migration-7984ad54a36b43a993154d55fa5b332c?pvs=4
