### ISSUE TITLE
Halborn audit

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#638]
```[tasklist]
- [ ] https://github.com/zeta-chain/zeta-node/issues/564
- [x] https://github.com/zeta-chain/zeta-node/issues/565
- [ ] https://github.com/zeta-chain/zeta-node/issues/566
- [ ] https://github.com/zeta-chain/zeta-node/issues/567
- [ ] https://github.com/zeta-chain/zeta-node/issues/568
- [ ] https://github.com/zeta-chain/zeta-node/issues/569
- [ ] https://github.com/zeta-chain/zeta-node/issues/570
- [ ] https://github.com/zeta-chain/zeta-node/issues/571
- [x] https://github.com/zeta-chain/zeta-node/issues/572
- [ ] https://github.com/zeta-chain/zeta-node/issues/573
- [ ] https://github.com/zeta-chain/zeta-node/issues/574
- [ ] https://github.com/zeta-chain/zeta-node/issues/575
- [ ] https://github.com/zeta-chain/zeta-node/issues/576
- [ ] https://github.com/zeta-chain/zeta-node/issues/577
- [ ] https://github.com/zeta-chain/zeta-node/issues/578
- [ ] https://github.com/zeta-chain/zeta-node/issues/579
```

**Comment by lumtis** [comment]
Closing, remaining issues will be considered in new milestone
