### ISSUE TITLE
Zellic audit

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#640]
```[tasklist]
- [x] https://github.com/zeta-chain/zeta-node/issues/580
- [x] https://github.com/zeta-chain/zeta-node/issues/581
- [x] https://github.com/zeta-chain/zeta-node/issues/582
- [x] https://github.com/zeta-chain/zeta-node/issues/604
- [x] https://github.com/zeta-chain/zeta-node/issues/583
- [x] https://github.com/zeta-chain/zeta-node/issues/584
- [x] https://github.com/zeta-chain/zeta-node/issues/585
- [ ] https://github.com/zeta-chain/zeta-node/issues/586
- [x] https://github.com/zeta-chain/zeta-node/issues/587
- [x] https://github.com/zeta-chain/zeta-node/issues/588
- [x] https://github.com/zeta-chain/zeta-node/issues/589
- [ ] https://github.com/zeta-chain/zeta-node/issues/590
```
