### ISSUE TITLE
Accountability for observer/keysigner validators

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#641]
We track votes, add judgement. Are you missing some of the observation, or faking it.

Key sign is a collaborative process, everybody need to do their job well. Every participant have their own view of who to blame. Network needs to decide who to blame.

The behavior of these two functions needs to be accounted for: reward/slash.

## Proposed solution

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/zeta-node/issues/713
- [ ] add observer accountability
- [ ] https://github.com/zeta-chain/zeta-node/issues/685
- [ ] https://github.com/zeta-chain/node/issues/836
- [ ] https://github.com/zeta-chain/node/issues/835
```

**Comment by lumtis** [comment]
Closing, remaining issues will be considered for new milestones
