### ISSUE TITLE
Whitelisting of ERC20 tokens

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#686]
Multiple steps in terms of transactions.

Update:

1. Edit the foreign coins structure.
2. In the contracts, we have ERC20Custody, need to whitelist there.

Strange things may happen if these things don't happen atomically.

> Pass a gov proposal or group policy on ZetaChain to whitelist an asset on a particular. This will add to the foreign coins struct. On a connected chain, custody contract needs to whitelist an ERC20. Need to make this atomic, so that nothing happens in between these two steps. Third step: activate on ZetaChain.

## Proposed solution

```[tasklist]
### Tasks
- [ ] add: zetaclient ERC20Custody whitelist methods
- [ ] add: whitelisting zetacore flow
- [ ] add: whitelisting zetaclient flow
```

Make it possible to whitelist ERC-20 tokens, but not sure how automated it should be.

Manual whitelisting is good enough.

"Automated" after it passes a gov proposal.
