### ISSUE TITLE
Mainnet (old)

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#692]
```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/zeta-node/issues/361
- [ ] https://github.com/zeta-chain/zeta-node/issues/344
- [ ] https://github.com/zeta-chain/zeta-node/issues/684
- [ ] https://github.com/zeta-chain/zeta-node/issues/645
- [ ] https://github.com/zeta-chain/zeta-node/issues/642
- [ ] https://github.com/zeta-chain/zeta-node/issues/641
- [ ] https://github.com/zeta-chain/zeta-node/issues/162
- [ ] https://github.com/zeta-chain/zeta-node/issues/675
- [ ] https://github.com/zeta-chain/zeta-node/issues/726
- [ ] https://github.com/zeta-chain/zeta-node/issues/734
- [ ] https://github.com/zeta-chain/zeta-node/issues/757
- [ ] https://github.com/zeta-chain/zeta-node/issues/768
- [ ] https://github.com/zeta-chain/zeta-node/issues/770
- [ ] https://github.com/zeta-chain/node/issues/920
- [ ] https://github.com/zeta-chain/node/issues/840
- [ ] https://github.com/zeta-chain/zeta-node/issues/769
```

**Comment by lumtis** [comment]
Closing as it seems no longer relevant
