### ISSUE TITLE
v5: Bitcoin support

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#722]
```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/zeta-node/issues/720
- [ ] https://github.com/zeta-chain/zeta-node/issues/730
- [ ] https://github.com/zeta-chain/zeta-node/issues/725
- [ ] https://github.com/zeta-chain/zeta-node/issues/773
- [ ] https://github.com/zeta-chain/zeta-node/issues/772
```

To complete before we encourage developers to migrate to Athens 3.
