### ISSUE TITLE
v8

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#838]
```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/686
- [ ] https://github.com/zeta-chain/node/issues/813
- [ ] https://github.com/zeta-chain/node/issues/839
- [ ] https://github.com/zeta-chain/node/issues/884
- [ ] https://github.com/zeta-chain/node/issues/832
- [ ] https://github.com/zeta-chain/node/issues/888
- [ ] https://github.com/zeta-chain/node/issues/894
- [ ] https://github.com/zeta-chain/node/issues/895
- [ ] https://github.com/zeta-chain/node/issues/924
- [ ] https://github.com/zeta-chain/node/issues/926
- [ ] https://github.com/zeta-chain/node/issues/938
```
