### ISSUE TITLE
arch: revise trust model to gradually move towards verification from majority voting

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/node#940]
Currently each external transactions (inbound, outbound) are each individually observed and voted on-chain to reach consensus on external events. 

A more trust-less process would be preferable, not only on the improved trust model, but also in terms of operations. Specifically, with verification available, observation (with proof) of external events are no long privileged to the Observer/Keysigner validator set. Rather, anyone can make such observations, provided they supply the merkle proof. This avoids the voting process, reduces the network operating cost, and makes fixing "missing observation" much easier. 

This proposal outlines a gradual plan to replace external txs observation voting with verification. 

First, instead of voting on individual transactions, the observers vote on block headers.  This is a middle ground between current majority voting on individual external txs and the full light client verification with out any majority voting on external events. 

Second, we enable optional "verifiable" outbound txs observation. When this proves to be reliable, we disable the voting on outbound tx observation and rely solely on verification. At the end of this step, the role of "observers" becomes more accurately "sequencers" which do no voting at all. 

Third, we enable optional "verifiable" inbound txs observation. When this proves to be reliable, we disable the voting on inbound tx observation and rely solely on verification. 

Fourth, chain-by-chain, we remove the voting on block headers, instead rely on light-client style verification of block headers. 

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/967
- [ ] https://github.com/zeta-chain/node/issues/968
- [ ] optional inbound tx confirmation verification
- [ ] removing majority vote on individual txs
```

**Comment by lumtis** [comment]
Closing as we have an epic for the task
