### ISSUE TITLE
v9

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#966]
```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/925
- [ ] https://github.com/zeta-chain/node/issues/972
- [ ] https://github.com/zeta-chain/node/issues/1011
- [ ] https://github.com/zeta-chain/node/pull/1031
- [ ] https://github.com/zeta-chain/node/pull/981
```
