### ISSUE TITLE
zetaclient improvements

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#971]
```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/965
- [ ] https://github.com/zeta-chain/node/issues/1015
- [x] https://github.com/zeta-chain/node/issues/1020
- [ ] https://github.com/zeta-chain/node/issues/1021
- [ ] https://github.com/zeta-chain/node/issues/1054
```

**Comment by lumtis** [comment]
Closing, adding the remaining issues in https://github.com/zeta-chain/node/issues/1611
